name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  read_value:
    runs-on: self-hosted
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: my-value-file
          path: ./artifact

      - name: Read the value
        run: |
          VALUE=$(cat ./artifact/my_value.txt)
          echo "The value is $VALUE"
