name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  create_value:
    runs-on: self-hosted
    steps:
      - name: Create a value file
        run: echo "example_value" > my_value.txt

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-value-file
          path: my_value.txt

